cc_test(
  name = "test_skiplist",
  srcs = ["test_skiplist.cc"],
  deps = [
    "//database:skiplist",
    "@com_google_googletest//:gtest_main",
  ],
)


cc_test(
  name = "test_sortlist",
  srcs = ["test_sortlist.cc"],
  deps = [
    "//database:skiplist",
    "//database:sortlist",
    "@com_google_googletest//:gtest_main",
  ],
)