cc_test(
  name = "test_skiplist",
  srcs = ["test_skiplist.cc"],
  deps = [
    ":skiplist",
    "@com_google_googletest//:gtest_main",
  ],
)

cc_library(
  name = "skiplist",
  hdrs = ["skiplist.h"],
)